// Terraform Variables
variable "gcp_credentials" {
  description = "GCP credentials needed by google provider"
}

variable "gcp_project" {
  description = "GCP project name"
}

variable "gcp_region" {
  description = "GCP region"
  default     = "us-east1"
}

// Google Provider Configuration
provider "google" {
  credentials = var.gcp_credentials
  project     = var.gcp_project
  region      = var.gcp_region
}

// -------------------------------------------------------------------
// 'Insert Terraform code generated by the Configuration Designer here
// -------------------------------------------------------------------

//--------------------------------------------------------------------
// Variables
variable "compute_instance_count" {}
variable "compute_instance_disk_image" {}
variable "compute_instance_disk_size" {}
variable "compute_instance_machine_type" {}




//--------------------------------------------------------------------
// Modules
module "compute_instance" {
  source  = "app.terraform.io/jdefrank-gcpdemo/compute-instance/google"
  version = "0.1.3"

  count = "${var.compute_instance_count}"
  disk_image = "${var.compute_instance_disk_image}"
  disk_size = "${var.compute_instance_disk_size}"
  machine_type = "${var.compute_instance_machine_type}"
  name_prefix = "quest-demo"
  subnetwork = "module.network_subnet.self_link"
}

module "network_firewall" {
  source  = "app.terraform.io/jdefrank-gcpdemo/network-firewall/google"
  version = "0.1.5"

  description = "demo-firewall-rule"
  name = "allow-80"
  network = "module.network.network_name"
  ports = [80]
  protocol = "tcp"
  source_ranges = ["0.0.0.0/0"]
}

module "network_subnet" {
  source  = "app.terraform.io/jdefrank-gcpdemo/network-subnet/google"
  version = "0.1.2"

  ip_cidr_range = "172.16.0.0/16"
  name = "quest-demo-subnet"
  vpc = "module.network.network_self_link"
}

module "network" {
  source  = "app.terraform.io/jdefrank-gcpdemo/network/google"
  version = "3.4.0"

  auto_create_subnetworks = "false"
  network_name = "quest-demo-network"
  project_id = "hc-7fffbf66a1e943c9b54c8fcdfa8"
  subnets = [module.network_subnet.self_link]
}


// -------------------------------------------------------------------

// Terraform outputs
output "network_name" {
  value = module.network.name
}

output "subnet_gateway_address" {
  value = module.network_subnet.gateway_address
}

output "firewall_self_link" {
  value = module.network_firewall.self_link
}

output "compute_instance_addresses" {
  value = module.compute_instance.addresses
}
